openapi: 3.0.3
info:
  version: 1.0.0
  title: '[Equipo 6] Gestión de clientes'
  description: |
    ## API REST para la gestión de clientes de talleres de mecánica
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://127.0.0.1:80/api/v1
    description: Servidor
tags:
  - name: 👤 Cliente
    description: Cliente
paths:
  /clientes:
    $ref: paths/clientes.yaml
  /clientes/{cliente_id}:
    $ref: paths/clientes_{cliente_id}.yaml
